services:
  db:
    image: postgres:17
    container_name: easeread-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-easeread}
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: easeread-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - db_data:/var/lib/redis/data

volumes:
  db_data:
